config/routes.rb
Rails.application.routes.draw do
  resources :receipts
  resources :payments
  resources :cash_registers
  resources :remission_notes
  resources :transfer_details
  resources :transfers
  resources :inventory_entry_details
  resources :inventory_entries
  resources :warehouses
  resources :sale_details
  resources :sales
  resources :quotation_details
  resources :quotations
  resources :products
  resources :clients
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "sales#new"
  
end

app/models/cash_register.rb
class CashRegister < ApplicationRecord
  belongs_to :sale
end

app/models/client.rb
class Client < ApplicationRecord
end

app/models/inventory_entry.rb
class InventoryEntry < ApplicationRecord
  belongs_to :warehouse
end

app/models/payment.rb
class Payment < ApplicationRecord
  belongs_to :sale
end

app/models/product.rb
class Product < ApplicationRecord
end

app/models/quotation.rb
class Quotation < ApplicationRecord
  belongs_to :client
end

app/models/quotation_detail.rb
class QuotationDetail < ApplicationRecord
  belongs_to :quotation
  belongs_to :product
end

app/models/receipt.rb
class Receipt < ApplicationRecord
  belongs_to :payment
end

app/models/remission_note.rb
class RemissionNote < ApplicationRecord
  belongs_to :sale
  belongs_to :warehouse
  belongs_to :client
end

app/models/sale.rb
class Sale < ApplicationRecord
  belongs_to :quotation
  belongs_to :client
end

app/models/sale_detail.rb
class SaleDetail < ApplicationRecord
  belongs_to :sale
  belongs_to :product
end

app/models/transfer.rb
class Transfer < ApplicationRecord
  belongs_to :origin_warehouse
  belongs_to :destination_warehouse
end

app/models/transfer_detail.rb
class TransferDetail < ApplicationRecord
  belongs_to :transfer
  belongs_to :product
end

app/models/warehouse.rb
class Warehouse < ApplicationRecord
end

app/controllers/transfer_details_controller.rb
class TransferDetailsController < ApplicationController
  before_action :set_transfer_detail, only: %i[ show edit update destroy ]

  # GET /transfer_details or /transfer_details.json
  def index
    @transfer_details = TransferDetail.all
  end

  # GET /transfer_details/1 or /transfer_details/1.json
  def show
  end

  # GET /transfer_details/new
  def new
    @transfer_detail = TransferDetail.new
  end

  # GET /transfer_details/1/edit
  def edit
  end

  # POST /transfer_details or /transfer_details.json
  def create
    @transfer_detail = TransferDetail.new(transfer_detail_params)

    respond_to do |format|
      if @transfer_detail.save
        format.html { redirect_to @transfer_detail, notice: "Transfer detail was successfully created." }
        format.json { render :show, status: :created, location: @transfer_detail }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @transfer_detail.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /transfer_details/1 or /transfer_details/1.json
  def update
    respond_to do |format|
      if @transfer_detail.update(transfer_detail_params)
        format.html { redirect_to @transfer_detail, notice: "Transfer detail was successfully updated." }
        format.json { render :show, status: :ok, location: @transfer_detail }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @transfer_detail.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /transfer_details/1 or /transfer_details/1.json
  def destroy
    @transfer_detail.destroy

    respond_to do |format|
      format.html { redirect_to transfer_details_path, status: :see_other, notice: "Transfer detail was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_transfer_detail
      @transfer_detail = TransferDetail.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def transfer_detail_params
      params.require(:transfer_detail).permit(:transfer_id, :product_id, :quantity, :subtotal)
    end
end

app/helpers/clientes_helper.rb
module ClientesHelper
end

app/helpers/clients_helper.rb
module ClientsHelper
end

app/helpers/payments_helper.rb
module PaymentsHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/receipts_helper.rb
module ReceiptsHelper
end

app/helpers/sales_helper.rb
module SalesHelper
end

app/helpers/transfer_details_helper.rb
module TransferDetailsHelper
end

app/helpers/venta_helper.rb
module VentaHelper
end

app/views/transfer_details/_form.html.erb
<%= form_with(model: transfer_detail) do |form| %>
  <% if transfer_detail.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(transfer_detail.errors.count, "error") %> prohibited this transfer_detail from being saved:</h2>

      <ul>
        <% transfer_detail.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :transfer_id, style: "display: block" %>
    <%= form.text_field :transfer_id %>
  </div>

  <div>
    <%= form.label :product_id, style: "display: block" %>
    <%= form.text_field :product_id %>
  </div>

  <div>
    <%= form.label :quantity, style: "display: block" %>
    <%= form.number_field :quantity %>
  </div>

  <div>
    <%= form.label :subtotal, style: "display: block" %>
    <%= form.text_field :subtotal %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/transfer_details/_transfer_detail.html.erb
<div id="<%= dom_id transfer_detail %>">
  <p>
    <strong>Transfer:</strong>
    <%= transfer_detail.transfer_id %>
  </p>

  <p>
    <strong>Product:</strong>
    <%= transfer_detail.product_id %>
  </p>

  <p>
    <strong>Quantity:</strong>
    <%= transfer_detail.quantity %>
  </p>

  <p>
    <strong>Subtotal:</strong>
    <%= transfer_detail.subtotal %>
  </p>

</div>

app/views/transfer_details/edit.html.erb
<h1>Editing transfer detail</h1>

<%= render "form", transfer_detail: @transfer_detail %>

<br>

<div>
  <%= link_to "Show this transfer detail", @transfer_detail %> |
  <%= link_to "Back to transfer details", transfer_details_path %>
</div>

app/views/transfer_details/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Transfer details</h1>

<div id="transfer_details">
  <% @transfer_details.each do |transfer_detail| %>
    <%= render transfer_detail %>
    <p>
      <%= link_to "Show this transfer detail", transfer_detail %>
    </p>
  <% end %>
</div>

<%= link_to "New transfer detail", new_transfer_detail_path %>

app/views/transfer_details/new.html.erb
<h1>New transfer detail</h1>

<%= render "form", transfer_detail: @transfer_detail %>

<br>

<div>
  <%= link_to "Back to transfer details", transfer_details_path %>
</div>

app/views/transfer_details/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @transfer_detail %>

<div>
  <%= link_to "Edit this transfer detail", edit_transfer_detail_path(@transfer_detail) %> |
  <%= link_to "Back to transfer details", transfer_details_path %>

  <%= button_to "Destroy this transfer detail", @transfer_detail, method: :delete %>
</div>