config/routes.rb
Rails.application.routes.draw do
  resources :receipts
  resources :payments
  resources :cash_registers
  resources :remission_notes
  resources :transfer_details
  resources :transfers
  resources :inventory_entry_details
  resources :inventory_entries
  resources :warehouses
  resources :sale_details
  resources :sales
  resources :quotation_details
  resources :quotations
  resources :products
  resources :clients
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "sales#new"
  
end

app/models/cash_register.rb
class CashRegister < ApplicationRecord
  belongs_to :sale
end

app/models/client.rb
class Client < ApplicationRecord
end

app/models/inventory_entry.rb
class InventoryEntry < ApplicationRecord
  belongs_to :warehouse
end

app/models/payment.rb
class Payment < ApplicationRecord
  belongs_to :sale
end

app/models/product.rb
class Product < ApplicationRecord
end

app/models/quotation.rb
class Quotation < ApplicationRecord
  belongs_to :client
end

app/models/quotation_detail.rb
class QuotationDetail < ApplicationRecord
  belongs_to :quotation
  belongs_to :product
end

app/models/receipt.rb
class Receipt < ApplicationRecord
  belongs_to :payment
end

app/models/remission_note.rb
class RemissionNote < ApplicationRecord
  belongs_to :sale
  belongs_to :warehouse
  belongs_to :client
end

app/models/sale.rb
class Sale < ApplicationRecord
  belongs_to :quotation
  belongs_to :client
end

app/models/sale_detail.rb
class SaleDetail < ApplicationRecord
  belongs_to :sale
  belongs_to :product
end

app/models/transfer.rb
class Transfer < ApplicationRecord
  belongs_to :origin_warehouse
  belongs_to :destination_warehouse
end

app/models/transfer_detail.rb
class TransferDetail < ApplicationRecord
  belongs_to :transfer
  belongs_to :product
end

app/models/warehouse.rb
class Warehouse < ApplicationRecord
end

app/controllers/quotations_controller.rb
class QuotationsController < ApplicationController
  before_action :set_quotation, only: %i[ show edit update destroy ]

  # GET /quotations or /quotations.json
  def index
    @quotations = Quotation.all
  end

  # GET /quotations/1 or /quotations/1.json
  def show
  end

  # GET /quotations/new
  def new
    @quotation = Quotation.new
  end

  # GET /quotations/1/edit
  def edit
  end

  # POST /quotations or /quotations.json
  def create
    @quotation = Quotation.new(quotation_params)

    respond_to do |format|
      if @quotation.save
        format.html { redirect_to @quotation, notice: "Quotation was successfully created." }
        format.json { render :show, status: :created, location: @quotation }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @quotation.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /quotations/1 or /quotations/1.json
  def update
    respond_to do |format|
      if @quotation.update(quotation_params)
        format.html { redirect_to @quotation, notice: "Quotation was successfully updated." }
        format.json { render :show, status: :ok, location: @quotation }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @quotation.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /quotations/1 or /quotations/1.json
  def destroy
    @quotation.destroy

    respond_to do |format|
      format.html { redirect_to quotations_path, status: :see_other, notice: "Quotation was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_quotation
      @quotation = Quotation.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def quotation_params
      params.require(:quotation).permit(:client_id, :date, :total)
    end
end

app/helpers/clientes_helper.rb
module ClientesHelper
end

app/helpers/clients_helper.rb
module ClientsHelper
end

app/helpers/payments_helper.rb
module PaymentsHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/quotations_helper.rb
module QuotationsHelper
end

app/helpers/receipts_helper.rb
module ReceiptsHelper
end

app/helpers/sales_helper.rb
module SalesHelper
end

app/helpers/venta_helper.rb
module VentaHelper
end

app/views/quotations/_form.html.erb
<%= form_with(model: quotation) do |form| %>
  <% if quotation.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(quotation.errors.count, "error") %> prohibited this quotation from being saved:</h2>

      <ul>
        <% quotation.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :client_id, style: "display: block" %>
    <%= form.text_field :client_id %>
  </div>

  <div>
    <%= form.label :date, style: "display: block" %>
    <%= form.datetime_field :date %>
  </div>

  <div>
    <%= form.label :total, style: "display: block" %>
    <%= form.text_field :total %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/quotations/_quotation.html.erb
<div id="<%= dom_id quotation %>">
  <p>
    <strong>Client:</strong>
    <%= quotation.client_id %>
  </p>

  <p>
    <strong>Date:</strong>
    <%= quotation.date %>
  </p>

  <p>
    <strong>Total:</strong>
    <%= quotation.total %>
  </p>

</div>

app/views/quotations/edit.html.erb
<h1>Editing quotation</h1>

<%= render "form", quotation: @quotation %>

<br>

<div>
  <%= link_to "Show this quotation", @quotation %> |
  <%= link_to "Back to quotations", quotations_path %>
</div>

app/views/quotations/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Quotations</h1>

<div id="quotations">
  <% @quotations.each do |quotation| %>
    <%= render quotation %>
    <p>
      <%= link_to "Show this quotation", quotation %>
    </p>
  <% end %>
</div>

<%= link_to "New quotation", new_quotation_path %>

app/views/quotations/new.html.erb
<h1>New quotation</h1>

<%= render "form", quotation: @quotation %>

<br>

<div>
  <%= link_to "Back to quotations", quotations_path %>
</div>

app/views/quotations/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @quotation %>

<div>
  <%= link_to "Edit this quotation", edit_quotation_path(@quotation) %> |
  <%= link_to "Back to quotations", quotations_path %>

  <%= button_to "Destroy this quotation", @quotation, method: :delete %>
</div>