config/routes.rb
Rails.application.routes.draw do
  resources :receipts
  resources :payments
  resources :cash_registers
  resources :remission_notes
  resources :transfer_details
  resources :transfers
  resources :inventory_entry_details
  resources :inventory_entries
  resources :warehouses
  resources :sale_details
  resources :sales
  resources :quotation_details
  resources :quotations
  resources :products
  resources :clients
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "sales#new"
  
end

app/models/cash_register.rb
class CashRegister < ApplicationRecord
  belongs_to :sale
end

app/models/client.rb
class Client < ApplicationRecord
end

app/models/inventory_entry.rb
class InventoryEntry < ApplicationRecord
  belongs_to :warehouse
end

app/models/payment.rb
class Payment < ApplicationRecord
  belongs_to :sale
end

app/models/product.rb
class Product < ApplicationRecord
end

app/models/quotation.rb
class Quotation < ApplicationRecord
  belongs_to :client
end

app/models/quotation_detail.rb
class QuotationDetail < ApplicationRecord
  belongs_to :quotation
  belongs_to :product
end

app/models/receipt.rb
class Receipt < ApplicationRecord
  belongs_to :payment
end

app/models/remission_note.rb
class RemissionNote < ApplicationRecord
  belongs_to :sale
  belongs_to :warehouse
  belongs_to :client
end

app/models/sale.rb
class Sale < ApplicationRecord
  belongs_to :quotation
  belongs_to :client
end

app/models/sale_detail.rb
class SaleDetail < ApplicationRecord
  belongs_to :sale
  belongs_to :product
end

app/models/transfer.rb
class Transfer < ApplicationRecord
  belongs_to :origin_warehouse
  belongs_to :destination_warehouse
end

app/models/transfer_detail.rb
class TransferDetail < ApplicationRecord
  belongs_to :transfer
  belongs_to :product
end

app/models/warehouse.rb
class Warehouse < ApplicationRecord
end

app/controllers/sales_controller.rb
class SalesController < ApplicationController
  before_action :set_sale, only: %i[ show edit update destroy ]

  # GET /sales or /sales.json
  def index
    @sales = Sale.all
  end

  # GET /sales/1 or /sales/1.json
  def show
  end

  # GET /sales/new
  def new
    @sale = Sale.new
  end

  # GET /sales/1/edit
  def edit
  end

  # POST /sales or /sales.json
  def create
    @sale = Sale.new(sale_params)

    respond_to do |format|
      if @sale.save
        format.html { redirect_to @sale, notice: "Sale was successfully created." }
        format.json { render :show, status: :created, location: @sale }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @sale.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /sales/1 or /sales/1.json
  def update
    respond_to do |format|
      if @sale.update(sale_params)
        format.html { redirect_to @sale, notice: "Sale was successfully updated." }
        format.json { render :show, status: :ok, location: @sale }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @sale.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /sales/1 or /sales/1.json
  def destroy
    @sale.destroy

    respond_to do |format|
      format.html { redirect_to sales_path, status: :see_other, notice: "Sale was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_sale
      @sale = Sale.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def sale_params
      params.require(:sale).permit(:quotation_id, :client_id, :date, :total, :payment_status, :client_name, :client_ci_nit)
    end
end

app/helpers/clientes_helper.rb
module ClientesHelper
end

app/helpers/clients_helper.rb
module ClientsHelper
end

app/helpers/payments_helper.rb
module PaymentsHelper
end

app/helpers/productos_helper.rb
module ProductosHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/receipts_helper.rb
module ReceiptsHelper
end

app/helpers/sales_helper.rb
module SalesHelper
end

app/helpers/venta_helper.rb
module VentaHelper
end

app/views/sales/_form.html.erb
<%= form_with(model: sale) do |form| %>
  <% if sale.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(sale.errors.count, "error") %> impidieron que esta venta se guardara:</h2>

      <ul>
        <% sale.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :quotation_id, "ID de Cotización", style: "display: block" %>
    <%= form.text_field :quotation_id %>
  </div>

  <div>
    <%= form.label :client_id, "ID de Cliente", style: "display: block" %>
    <%= form.text_field :client_id %>
  </div>

  <div>
    <%= form.label :date, "Fecha", style: "display: block" %>
    <%= form.datetime_field :date %>
  </div>

  <div>
    <%= form.label :total, "Total", style: "display: block" %>
    <%= form.text_field :total %>
  </div>

  <div>
    <%= form.label :payment_status, "Estado de Pago", style: "display: block" %>
    <%= form.text_field :payment_status %>
  </div>

  <div>
    <%= form.label :client_name, "Nombre del Cliente", style: "display: block" %>
    <%= form.text_field :client_name %>
  </div>

  <div>
    <%= form.label :client_ci_nit, style: "display: block" %>
    <%= form.text_field :client_ci_nit %>
  </div>

  <div class="actions">
    <%= form.submit "Guardar Venta" %>
  </div>
<% end %>

app/views/sales/_sale.html.erb
<div id="<%= dom_id sale %>">
  <p>
    <strong>Cotización:</strong>
    <%= sale.quotation_id %>
  </p>

  <p>
    <strong>Cliente:</strong>
    <%= sale.client_id %>
  </p>

  <p>
    <strong>Fecha:</strong>
    <%= sale.date %>
  </p>

  <p>
    <strong>Total:</strong>
    <%= sale.total %>
  </p>

  <p>
    <strong>Estado de pago:</strong>
    <%= sale.payment_status %>
  </p>

  <p>
    <strong>Nombre del cliente:</strong>
    <%= sale.client_name %>
  </p>

</div>

app/views/sales/edit.html.erb
<h1>Editing sale</h1>

<%= render "form", sale: @sale %>

<br>

<div>
  <%= link_to "Show this sale", @sale %> |
  <%= link_to "Back to sales", sales_path %>
</div>

app/views/sales/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Sales</h1>

<div id="sales">
  <% @sales.each do |sale| %>
    <%= render sale %>
    <p>
      <%= link_to "Show this sale", sale %>
    </p>
  <% end %>
</div>

<%= link_to "New sale", new_sale_path %>

app/views/sales/new.html.erb
<h1>Nueva venta</h1>

<%= render "form", sale: @sale %>

<br>

<div>
  <%= link_to "Back to sales", sales_path %>
</div>

app/views/sales/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @sale %>

<div>
  <%= link_to "Edit this sale", edit_sale_path(@sale) %> |
  <%= link_to "Back to sales", sales_path %>

  <%= button_to "Destroy this sale", @sale, method: :delete %>
</div>