config/routes.rb
Rails.application.routes.draw do
  resources :receipts
  resources :payments
  resources :cash_registers
  resources :remission_notes
  resources :transfer_details
  resources :transfers
  resources :inventory_entry_details
  resources :inventory_entries
  resources :warehouses
  resources :sale_details
  resources :sales
  resources :quotation_details
  resources :quotations
  resources :products
  resources :clients
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "sales#new"
  
end

app/models/cash_register.rb
class CashRegister < ApplicationRecord
  belongs_to :sale
end

app/models/client.rb
class Client < ApplicationRecord
end

app/models/inventory_entry.rb
class InventoryEntry < ApplicationRecord
  belongs_to :warehouse
end

app/models/inventory_entry_detail.rb
class InventoryEntryDetail < ApplicationRecord
  belongs_to :inventory_entry
  belongs_to :product
end

app/models/payment.rb
class Payment < ApplicationRecord
  belongs_to :sale
end

app/models/product.rb
class Product < ApplicationRecord
end

app/models/quotation.rb
class Quotation < ApplicationRecord
  belongs_to :client
end

app/models/receipt.rb
class Receipt < ApplicationRecord
  belongs_to :payment
end

app/models/remission_note.rb
class RemissionNote < ApplicationRecord
  belongs_to :sale
  belongs_to :warehouse
  belongs_to :client
end

app/models/sale.rb
class Sale < ApplicationRecord
  belongs_to :quotation
  belongs_to :client
end

app/models/sale_detail.rb
class SaleDetail < ApplicationRecord
  belongs_to :sale
  belongs_to :product
end

app/models/transfer.rb
class Transfer < ApplicationRecord
  belongs_to :origin_warehouse
  belongs_to :destination_warehouse
end

app/models/transfer_detail.rb
class TransferDetail < ApplicationRecord
  belongs_to :transfer
  belongs_to :product
end

app/models/warehouse.rb
class Warehouse < ApplicationRecord
end

app/controllers/inventory_entry_details_controller.rb
class InventoryEntryDetailsController < ApplicationController
  before_action :set_inventory_entry_detail, only: %i[ show edit update destroy ]

  # GET /inventory_entry_details or /inventory_entry_details.json
  def index
    @inventory_entry_details = InventoryEntryDetail.all
  end

  # GET /inventory_entry_details/1 or /inventory_entry_details/1.json
  def show
  end

  # GET /inventory_entry_details/new
  def new
    @inventory_entry_detail = InventoryEntryDetail.new
  end

  # GET /inventory_entry_details/1/edit
  def edit
  end

  # POST /inventory_entry_details or /inventory_entry_details.json
  def create
    @inventory_entry_detail = InventoryEntryDetail.new(inventory_entry_detail_params)

    respond_to do |format|
      if @inventory_entry_detail.save
        format.html { redirect_to @inventory_entry_detail, notice: "Inventory entry detail was successfully created." }
        format.json { render :show, status: :created, location: @inventory_entry_detail }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @inventory_entry_detail.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /inventory_entry_details/1 or /inventory_entry_details/1.json
  def update
    respond_to do |format|
      if @inventory_entry_detail.update(inventory_entry_detail_params)
        format.html { redirect_to @inventory_entry_detail, notice: "Inventory entry detail was successfully updated." }
        format.json { render :show, status: :ok, location: @inventory_entry_detail }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @inventory_entry_detail.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /inventory_entry_details/1 or /inventory_entry_details/1.json
  def destroy
    @inventory_entry_detail.destroy

    respond_to do |format|
      format.html { redirect_to inventory_entry_details_path, status: :see_other, notice: "Inventory entry detail was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_inventory_entry_detail
      @inventory_entry_detail = InventoryEntryDetail.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def inventory_entry_detail_params
      params.require(:inventory_entry_detail).permit(:inventory_entry_id, :product_id, :quantity, :subtotal)
    end
end

app/helpers/clientes_helper.rb
module ClientesHelper
end

app/helpers/clients_helper.rb
module ClientsHelper
end

app/helpers/inventory_entry_details_helper.rb
module InventoryEntryDetailsHelper
end

app/helpers/payments_helper.rb
module PaymentsHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/receipts_helper.rb
module ReceiptsHelper
end

app/helpers/sales_helper.rb
module SalesHelper
end

app/helpers/venta_helper.rb
module VentaHelper
end

app/views/inventory_entry_details/_form.html.erb
<%= form_with(model: inventory_entry_detail) do |form| %>
  <% if inventory_entry_detail.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(inventory_entry_detail.errors.count, "error") %> prohibited this inventory_entry_detail from being saved:</h2>

      <ul>
        <% inventory_entry_detail.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :inventory_entry_id, style: "display: block" %>
    <%= form.text_field :inventory_entry_id %>
  </div>

  <div>
    <%= form.label :product_id, style: "display: block" %>
    <%= form.text_field :product_id %>
  </div>

  <div>
    <%= form.label :quantity, style: "display: block" %>
    <%= form.number_field :quantity %>
  </div>

  <div>
    <%= form.label :subtotal, style: "display: block" %>
    <%= form.text_field :subtotal %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/inventory_entry_details/_inventory_entry_detail.html.erb
<div id="<%= dom_id inventory_entry_detail %>">
  <p>
    <strong>Inventory entry:</strong>
    <%= inventory_entry_detail.inventory_entry_id %>
  </p>

  <p>
    <strong>Product:</strong>
    <%= inventory_entry_detail.product_id %>
  </p>

  <p>
    <strong>Quantity:</strong>
    <%= inventory_entry_detail.quantity %>
  </p>

  <p>
    <strong>Subtotal:</strong>
    <%= inventory_entry_detail.subtotal %>
  </p>

</div>

app/views/inventory_entry_details/edit.html.erb
<h1>Editing inventory entry detail</h1>

<%= render "form", inventory_entry_detail: @inventory_entry_detail %>

<br>

<div>
  <%= link_to "Show this inventory entry detail", @inventory_entry_detail %> |
  <%= link_to "Back to inventory entry details", inventory_entry_details_path %>
</div>

app/views/inventory_entry_details/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Inventory entry details</h1>

<div id="inventory_entry_details">
  <% @inventory_entry_details.each do |inventory_entry_detail| %>
    <%= render inventory_entry_detail %>
    <p>
      <%= link_to "Show this inventory entry detail", inventory_entry_detail %>
    </p>
  <% end %>
</div>

<%= link_to "New inventory entry detail", new_inventory_entry_detail_path %>

app/views/inventory_entry_details/new.html.erb
<h1>New inventory entry detail</h1>

<%= render "form", inventory_entry_detail: @inventory_entry_detail %>

<br>

<div>
  <%= link_to "Back to inventory entry details", inventory_entry_details_path %>
</div>

app/views/inventory_entry_details/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @inventory_entry_detail %>

<div>
  <%= link_to "Edit this inventory entry detail", edit_inventory_entry_detail_path(@inventory_entry_detail) %> |
  <%= link_to "Back to inventory entry details", inventory_entry_details_path %>

  <%= button_to "Destroy this inventory entry detail", @inventory_entry_detail, method: :delete %>
</div>